clc
clear
close all

puretonesGUI = figure('units','normalized','position',[0.2 0.32 0.5 0.6],...
    'menubar','none','numbertitle','off','name','ABR Specifications');

fsz = 12;
fszv = 12;

xtext = 0.00;
Ltext = 0.39;
xval = xtext + Ltext;
Lval = 0.15;
a = 0.9; da = 0.08;

min_Freq_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Minimum Frequency (kHz) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

min_Freq_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',4,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','min_Freq');

a = a-da;
max_Freq_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Maximum Frequency (kHz) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

max_Freq_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',64,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','max_Freq');

a = a-da;
Freq_per_Oct_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Frequency per Octave = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Freq_per_Oct_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','Freq_per_Oct');

a = a-da;
Amp_Array_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Amplitude Array (dB) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Amp_Array_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','[20:10:90]','units','normalized','position',[xval a 1.0*Lval 0.065],...
    'fontsize',fszv,'tag','Amp_Array');

a = a-da;
ramp_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','ramp/gate duration (msec) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
	'Max',2,'Min',0,...
    'horizontalalignment','right');

ramp_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1.5,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','ramp');

a = a-da;
Pulse_Dur_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Pulse duration (msec) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Pulse_Dur_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',6,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','Pulse_Dur');

a = a-da;
ClickDur_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Click Duration (msec) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

ClickDur_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','ClickDur');

a = a-da;
Rate_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Rate (stim/s) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Rate_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',21,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','Rate');

a = a-da;
Ntone_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Tone Trials = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Ntone_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1024,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','Ntone');

a = a-da;
Nclick_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Clicks Trials = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Nclick_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1024,'units','normalized','position',[xval a Lval 0.065],...
    'fontsize',fszv,'tag','Nclick');

Randomized_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Randomized  ', 'units','normalized',...
    'position',[xtext+0.095 0.0 Ltext-0.26 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right');

Randomized_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',0,'units','normalized','position',[xtext+Ltext-0.17 0.003 0.1 0.072],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','Randomized');


Click_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Click  ', 'units','normalized',...
    'position',[xtext+0.125 0.055 Ltext-0.29 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right');

Click_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',1,'units','normalized','position',[xtext+Ltext-0.17 0.055 0.05 0.08],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','Click');


fileno_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','File Number = ', 'units','normalized',...
    'position',[xtext+0.28 0.0 Ltext-0.24 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','left');

fileno_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','01','units','normalized','position',[xtext+0.43 0.015 0.12 0.055],...
    'fontsize',fszv,'tag','fileno');


xnotes = xval + Lval + 0.05;
Notes_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Notes: ', 'units','normalized',...
    'position',[xnotes 0.625 .1 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Notes_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','','units','normalized',...
	'position',[xnotes 0.1 .4 0.55],...
	'Max',2, 'Min',0, 'horizontalalignment','left', ...
    'fontsize',fszv,'tag','Notes');

xSpeaker = xval + Lval + 0.05;
Speaker_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Speaker Name:  ', 'units','normalized',...
    'position',[xSpeaker 0.9 .2 0.055],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Speaker_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','ES1-A','units','normalized',...
	'position',[xSpeaker+0.15 0.91 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'fontsize',fszv,'tag','Speaker');


run_button = uicontrol('parent',puretonesGUI,'style','pushbutton',...
    'string','Run', 'units','normalized',...
    'position',[0.65 0.005 0.3 0.08],'fontsize',fsz,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right','tag','run_button',...
    'Callback',@run_button_Callback_ABR_Tones);





