clc
clear
close all

puretonesGUI = figure('units','normalized','position',[0.25 0.25 0.55 0.55],...
    'menubar','none','numbertitle','off','name','Piecewise FM Sweeps Specifications');

xtext = 0.00;
Ltext = 0.39;
xval = xtext + Ltext;
Lval = 0.15;

ytext = 0.915;
Htext = 0.055;
yval = ytext + Htext;
Hval = 0.065;

RowSpace = Htext*1.5;

min_Freq_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Minimum Frequency (kHz) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

min_Freq_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',4,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','min_Freq');

ytext = ytext - RowSpace;
max_Freq_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Maximum Frequency (kHz) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

max_Freq_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',32,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','max_Freq');

ytext = ytext - RowSpace;
Freq_per_Oct_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Frequency per Octave = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Freq_per_Oct_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','Freq_per_Oct');

ytext = ytext - RowSpace;
BW_Oct_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Sweep BandWidth (Octave) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

BW_Oct_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','BW_Oct');

ytext = ytext - RowSpace;
Amp_Array_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Amplitude Array (dB) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Amp_Array_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','[60]','units','normalized','position',[xval ytext Lval Hval],...
    'fontsize',7,'tag','Amp_Array');

ytext = ytext - RowSpace;
Pulse_Dur_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Pulse Duration (msec) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Pulse_Dur_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',20,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','Pulse_Dur');

ytext = ytext - RowSpace;
ramp_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','ramp (msec) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

ramp_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','ramp');

ytext = ytext - RowSpace;
ISI_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','ISI (msec) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

ISI_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',5000,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','ISI');

ytext = ytext - RowSpace;
jitter_percentage_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Jitter (% Silence) = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

jitter_percentage_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',20,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','jitter_percentage');

ytext = ytext - RowSpace;
Ntrials_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of Trials = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Ntrials_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',30,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','Ntrials');

fileno_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','File Number = ', 'units','normalized',...
    'position',[xtext+0.29 0.0 Ltext-0.16 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

fileno_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','01','units','normalized','position',[xtext+0.525 0.015 0.12 0.055],...
    'tag','fileno');

xSpeaker = xval + Lval + 0.05;
Speaker_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Speaker Name:  ', 'units','normalized',...
    'position',[xSpeaker 0.9 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Speaker_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','ES1-A','units','normalized',...
	'position',[xSpeaker+0.15 0.91 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','Speaker');

xFsCam = xval + Lval + 0.05;
FsCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Camera Fs (f/s): ', 'units','normalized',...
    'position',[xFsCam 0.84 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


FsCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',30,'units','normalized',...
	'position',[xFsCam+0.15 0.85 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','FsCam');

xnFrames = xval + Lval + 0.05;
nFrames_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','nFrames: ', 'units','normalized',...
    'position',[xnFrames 0.78 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


nFrames_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',7000,'units','normalized',...
	'position',[xnFrames+0.15 0.79 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','nFrames');

xNCam = xval + Lval + 0.05;
NCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of Cam files:', 'units','normalized',...
    'position',[xNCam 0.72 0.2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');

NCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',5,'units','normalized','position',[xNCam+0.15 0.73 Lval 0.055],...
    'tag','NCam');

xnotes = xval + Lval + 0.05;
Notes_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Notes: ', 'units','normalized',...
    'position',[xnotes 0.6750 .1 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Notes_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','','units','normalized',...
	'position',[xnotes 0.1 .4 0.60],...
	'Max',2, 'Min',0, 'horizontalalignment','left', ...
    'tag','Notes');

% check-boxs
xtext = xtext+0.01;
Ltext = 0.1;
ytext = 0;

xval = xtext+Ltext;
Lval = 0.03;
Hval = 0.08;
Randomized_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Randomized  ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right');

Randomized_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',1,'units','normalized','position',[xval ytext Lval Hval],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','Randomized');

xtext = xval+Lval;
UpDown_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Up Down  ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right');

xval = xtext+Ltext;
UpDown_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',1,'units','normalized','position',[xval ytext Lval Hval],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','UpDown');

run_button = uicontrol('parent',puretonesGUI,'style','pushbutton',...
    'string','Run', 'units','normalized',...
    'position',[0.65 0.005 0.3 0.08],'fontsize',12,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right','tag','run_button',...
    'Callback',@run_button_Callback);





