clc
clear
close all

puretonesGUI = figure('units','normalized','position',[0.2 0.3 0.55 0.45],...
    'menubar','none','numbertitle','off','name','Pure Tones Specifications');

xtext = 0.00;
Ltext = 0.39;
xval = xtext + Ltext;
Lval = 0.15;
a = 0.92;
d = 0.076;

MMPercent_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Mismatch Percent = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

MMPercent_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',12.5,'units','normalized','position',[xval a Lval 0.065],...
    'tag','MMPercent');

a = a-d;
FI_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','block AB Freq I (kHz) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

FI_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',3.6,'units','normalized','position',[xval a Lval 0.065],...
    'tag','FI');

a = a-d;
FII_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','block AB Freq II (kHz) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

FII_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',5.1,'units','normalized','position',[xval a Lval 0.065],...
    'tag','FII');

a = a-d;
FC_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','block C Freq list = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

FC_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','[3.3:0.3:5.4]','units','normalized','position',[xval a Lval 0.065],...
    'tag','FC');

a = a-d;
Amp_Array_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Amplitude Array (dB) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Amp_Array_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','[70]','units','normalized','position',[xval a 1.0*Lval 0.065],...
    'tag','Amp_Array');

a = a-d;
ramp_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string',['ramp (msec)(change TDT) = '], 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
	'Max',2,'Min',0,...
    'horizontalalignment','right');

ramp_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',5,'units','normalized','position',[xval a Lval 0.065],...
    'tag','ramp');

a = a-d;
Pulse_Dur_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Pulse Duration (msec) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Pulse_Dur_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',100,'units','normalized','position',[xval a Lval 0.065],...
    'tag','Pulse_Dur');

a = a-d;
ISI_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','ISI (msec) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

ISI_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1000,'units','normalized','position',[xval a Lval 0.065],...
    'tag','ISI');

a = a-d;
jitter_percentage_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Jitter (% Silence) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

jitter_percentage_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',0,'units','normalized','position',[xval a Lval 0.065],...
    'tag','jitter_percentage');

a = a-d;
NperCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of stim per recording = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

NperCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',400,'units','normalized','position',[xval a Lval 0.065],...
    'tag','NperCam');

a = a-d;
nSponB_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of Spon in the Begining = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

nSponB_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',0,'units','normalized','position',[xval a Lval 0.065],...
    'tag','nSponB');

a = a-d;
nSponE_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of Spon in the End = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

nSponE_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',0,'units','normalized','position',[xval a Lval 0.065],...
    'tag','nSponE');

Randomized_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Randomized  ', 'units','normalized',...
    'position',[xtext 0.0 Ltext-0.29 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');

Randomized_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',1,'units','normalized','position',[xval-0.29 0 0.1 0.08],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','Randomized');

seed_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Seed Number = ', 'units','normalized',...
    'position',[xtext+0.25 0.0 Ltext-0.16 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','left');

seed_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','01','units','normalized','position',[xtext+0.38 0.012 0.06 0.055],...
    'tag','seed');

fileno_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','File Number = ', 'units','normalized',...
    'position',[xtext+0.46 0.0 Ltext-0.16 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','left');

fileno_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','01','units','normalized','position',[xtext+0.58 0.012 0.06 0.055],...
    'tag','fileno');


xnotes = xval + Lval + 0.05;
Notes_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Notes: ', 'units','normalized',...
    'position',[xnotes 0.625 .1 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Notes_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','','units','normalized',...
	'position',[xnotes 0.1 .4 0.55],...
	'Max',2, 'Min',0, 'horizontalalignment','left', ...
    'tag','Notes');

xSpeaker = xval + Lval + 0.05;
Speaker_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Speaker Name:  ', 'units','normalized',...
    'position',[xSpeaker 0.9 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Speaker_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','ES1-A-40cm','units','normalized',...
	'position',[xSpeaker+0.15 0.91 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','Speaker');

xFsCam = xval + Lval + 0.05;
FsCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Camera Fs (f/s): ', 'units','normalized',...
    'position',[xFsCam 0.84 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


FsCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',30,'units','normalized',...
	'position',[xFsCam+0.15 0.85 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','FsCam');

xnFrames = xval + Lval + 0.05;
nFrames_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','nFrames: ', 'units','normalized',...
    'position',[xnFrames 0.78 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


nFrames_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',13500,'units','normalized',...
	'position',[xnFrames+0.15 0.79 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','nFrames');

NCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','NCam: ', 'units','normalized',...
    'position',[xnFrames 0.72 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


NCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',3,'units','normalized',...
	'position',[xnFrames+0.15 0.73 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','NCam');


run_button = uicontrol('parent',puretonesGUI,'style','pushbutton',...
    'string','Run', 'units','normalized',...
    'position',[0.79 0.005 0.2 0.08],'fontsize',12,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right','tag','run_button',...
    'Callback',@run_button_Callback);





