clc
clear
close all

puretonesGUI = figure('units','normalized','position',[0.25 0.25 0.5 0.55],...
    'menubar','none','numbertitle','off','name','STRFs Specifications');

xtext = 0.025;
Ltext = 0.15;
xval = xtext + Ltext;
Lval = 0.3;

ytext = 0.915;
Htext = 0.055;
yval = ytext + Htext;
Hval = 0.065;

RowSpace = Htext*1.5;

seed_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','seed number = ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

seed_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',1,'units','normalized','position',[xval ytext Lval Hval],...
    'tag','seed');

ytext = ytext - RowSpace;
Stim_panel = uipanel('Title','STRF Stims','units','normalized',...
    'position',[xtext ytext-Htext*3 Ltext+Lval Htext*4]);

xtextP = 0.25; ytextP = 0.8; LtextP = 0.3; HtextP = .15;
xvalP  = xtextP+LtextP; LvalP = 0.15; HvalP =0.15;
RowSpaceP = 0.25;
DRCs_txt = uicontrol('parent',Stim_panel,'style','text',...
    'string','DRCs ', 'units','normalized',...
    'position',[xtextP ytextP LtextP HtextP],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),...
    'horizontalalignment','right');

DRCs_h = uicontrol('parent',Stim_panel,'style','checkbox',...
    'value',1,'units','normalized','position',[xvalP ytextP LvalP HvalP],...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),'tag','DRCs');

ytextP = ytextP - RowSpaceP;
DMRs_txt = uicontrol('parent',Stim_panel,'style','text',...
    'string','DMRs ', 'units','normalized',...
    'position',[xtextP ytextP LtextP HtextP],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),...
    'horizontalalignment','right');

DMRs_h = uicontrol('parent',Stim_panel,'style','checkbox',...
    'value',1,'units','normalized','position',[xvalP ytextP LvalP HvalP],...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),'tag','DMRs');

ytextP = ytextP - RowSpaceP;
FM_txt = uicontrol('parent',Stim_panel,'style','text',...
    'string','FM Sweeps ', 'units','normalized',...
    'position',[xtextP ytextP LtextP HtextP],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),...
    'horizontalalignment','right');

FM_h = uicontrol('parent',Stim_panel,'style','checkbox',...
    'value',1,'units','normalized','position',[xvalP ytextP LvalP HvalP],...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),'tag','FM');

ytextP = ytextP - RowSpaceP;
Vocal_txt = uicontrol('parent',Stim_panel,'style','text',...
    'string','Vocalizations ', 'units','normalized',...
    'position',[xtextP ytextP LtextP HtextP],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),...
    'horizontalalignment','right');

Vocal_h = uicontrol('parent',Stim_panel,'style','checkbox',...
    'value',1,'units','normalized','position',[xvalP ytextP LvalP HvalP],...
    'backgroundcolor',get(Stim_panel,'backgroundcolor'),'tag','Vocal');


fileno_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','File Number = ', 'units','normalized',...
    'position',[xtext+0.5 0.0 Ltext*1.5 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

fileno_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','01','units','normalized','position',[xtext+0.5+Ltext*1.5 0.015 0.05 0.055],...
    'tag','fileno');

xSpeaker = xval + Lval + 0.05;
Speaker_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Speaker Name:  ', 'units','normalized',...
    'position',[xSpeaker 0.9 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Speaker_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','ES1-A','units','normalized',...
	'position',[xSpeaker+0.15 0.91 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','Speaker');

xFsCam = xval + Lval + 0.05;
FsCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Camera Fs (f/s): ', 'units','normalized',...
    'position',[xFsCam 0.84 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


FsCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',30,'units','normalized',...
	'position',[xFsCam+0.15 0.85 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','FsCam');

xnFrames = xval + Lval + 0.05;
nFrames_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','nFrames: ', 'units','normalized',...
    'position',[xnFrames 0.78 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


nFrames_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',7000,'units','normalized',...
	'position',[xnFrames+0.15 0.79 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','nFrames');

xNCam = xval + Lval + 0.05;
NCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','# of Cam files:', 'units','normalized',...
    'position',[xNCam 0.72 0.2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');

NCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',5,'units','normalized','position',[xNCam+0.15 0.73 Lval 0.055],...
    'tag','NCam');

xnotes = xval + Lval + 0.05;
Notes_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Notes: ', 'units','normalized',...
    'position',[xnotes 0.6750 .1 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Notes_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','','units','normalized',...
	'position',[xnotes 0.1 .45 0.60],...
	'Max',2, 'Min',0, 'horizontalalignment','left', ...
    'tag','Notes');

% check-boxs
xtext = xtext+0.43;
Ltext = 0.12;
ytext = 0;
xval = xtext+Ltext;
Lval = 0.03;
Hval = 0.08;
Randomized_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Randomized  ', 'units','normalized',...
    'position',[xtext ytext Ltext Htext],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right');

Randomized_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',0,'units','normalized','position',[xval ytext Lval Hval],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','Randomized');


run_button = uicontrol('parent',puretonesGUI,'style','pushbutton',...
    'string','Run', 'units','normalized',...
    'position',[0.825 0.005 0.15 0.08],'fontsize',12,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right','tag','run_button',...
    'Callback',@run_button_Callback);





