clc
clear
close all

puretonesGUI = figure('units','normalized','position',[0.2 0.35 0.55 0.45],...
    'menubar','none','numbertitle','off','name','Pure Tones Specifications');

xtext = 0.00;
Ltext = 0.39;
xval = xtext + Ltext;
Lval = 0.15;
a = 0.9;

min_Freq_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Minimum Frequency (kHz) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

min_Freq_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',4,'units','normalized','position',[xval a Lval 0.065],...
    'tag','min_Freq');

a = a-0.08;
max_Freq_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Maximum Frequency (kHz) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

max_Freq_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',32,'units','normalized','position',[xval a Lval 0.065],...
    'tag','max_Freq');

a = a-0.08;
Freq_per_Oct_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Frequency per Octave = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Freq_per_Oct_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',0.667,'units','normalized','position',[xval a Lval 0.065],...
    'tag','Freq_per_Oct');

a = a-0.08;
Amp_Array_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Amplitude Array (dB) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Amp_Array_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','[70]','units','normalized','position',[xval a 1.0*Lval 0.065],...
    'fontsize',7,'tag','Amp_Array');

a = a-0.08;
ramp_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string',['ramp (msec)(change TDT) = '], 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
	'Max',2,'Min',0,...
    'horizontalalignment','right');

ramp_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',5,'units','normalized','position',[xval a Lval 0.065],...
    'tag','ramp');

a = a-0.08;
Pulse_Dur_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Pulse Duration (msec) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Pulse_Dur_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',100,'units','normalized','position',[xval a Lval 0.065],...
    'tag','Pulse_Dur');

a = a-0.08;
ISI_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','ISI (msec) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

ISI_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',4000,'units','normalized','position',[xval a Lval 0.065],...
    'tag','ISI','enable','off');

a = a-0.08;
jitter_percentage_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Jitter (% Silence) = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

jitter_percentage_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',12.5,'units','normalized','position',[xval a Lval 0.065],...
    'tag','jitter_percentage','enable','off');

a = a-0.08;
Ntrials_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of Trials = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

Ntrials_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',10,'units','normalized','position',[xval a Lval 0.065],...
    'tag','Ntrials','enable','off');

a = a-0.08;
nContStimB_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of Continuous Stim in the Begining = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

nContStimB_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',2,'units','normalized','position',[xval a Lval 0.065],...
    'tag','nContStimB','enable','off');

a = a-0.08;
nContStimE_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Number of Continuous Stim in the End = ', 'units','normalized',...
    'position',[xtext a Ltext 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','right');

nContStimE_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',0,'units','normalized','position',[xval a Lval 0.065],...
    'tag','nContStimE','enable','off');

Randomized_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Randomized  ', 'units','normalized',...
    'position',[xtext 0.0 Ltext-0.29 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');

Randomized_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',1,'units','normalized','position',[xval-0.29 0 0.1 0.08],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','Randomized','enable','off');

Noise_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Noise  ', 'units','normalized',...
    'position',[xtext+0.15 0.0 Ltext-0.34 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');

Noise_h = uicontrol('parent',puretonesGUI,'style','checkbox',...
    'value',1,'units','normalized','position',[xval-0.19 0 0.1 0.08],...
    'backgroundcolor',get(puretonesGUI,'color'),'tag','Noise','enable','off');

seed_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Seed Number = ', 'units','normalized',...
    'position',[xtext+0.25 0.0 Ltext-0.16 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','left');

seed_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','01','units','normalized','position',[xtext+0.38 0.012 0.06 0.055],...
    'tag','seed');

fileno_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','File Number = ', 'units','normalized',...
    'position',[xtext+0.46 0.0 Ltext-0.16 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'horizontalalignment','left');

fileno_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','01','units','normalized','position',[xtext+0.58 0.012 0.06 0.055],...
    'tag','fileno');


xnotes = xval + Lval + 0.05;
Notes_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Notes: ', 'units','normalized',...
    'position',[xnotes 0.625 .1 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Notes_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','','units','normalized',...
	'position',[xnotes 0.1 .4 0.55],...
	'Max',2, 'Min',0, 'horizontalalignment','left', ...
    'tag','Notes');

xSpeaker = xval + Lval + 0.05;
Speaker_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Speaker Name:  ', 'units','normalized',...
    'position',[xSpeaker 0.9 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


Speaker_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string','ES1-A-40cm','units','normalized',...
	'position',[xSpeaker+0.15 0.91 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','Speaker');

xFsCam = xval + Lval + 0.05;
FsCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','Camera Fs (f/s): ', 'units','normalized',...
    'position',[xFsCam 0.84 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


FsCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',30,'units','normalized',...
	'position',[xFsCam+0.15 0.85 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','FsCam');

xnFrames = xval + Lval + 0.05;
nFrames_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','nFrames: ', 'units','normalized',...
    'position',[xnFrames 0.78 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


nFrames_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',7000,'units','normalized',...
	'position',[xnFrames+0.15 0.79 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','nFrames');

NCam_txt = uicontrol('parent',puretonesGUI,'style','text',...
    'string','NCam: ', 'units','normalized',...
    'position',[xnFrames 0.72 .2 0.055],'fontsize',9,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','left');


NCam_h = uicontrol('parent',puretonesGUI,'style','edit',...
    'string',7,'units','normalized',...
	'position',[xnFrames+0.15 0.73 Lval 0.055],...
	'Max',1, 'Min',0, 'horizontalalignment','center', ...
    'tag','NCam');


run_button = uicontrol('parent',puretonesGUI,'style','pushbutton',...
    'string','Run', 'units','normalized',...
    'position',[0.79 0.005 0.2 0.08],'fontsize',12,...
    'fontname','times new roman',...
    'backgroundcolor',get(puretonesGUI,'color'),...
    'ForegroundColor','b',...
    'horizontalalignment','right','tag','run_button',...
    'Callback',@run_button_Callback);





